# Generated by Django 5.1.3 on 2024-11-18 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Music", "Music"),
                            ("Sports", "Sports"),
                            ("Seminars", "Seminars"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                        ],
                        default="None",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attending_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
